client_id = "832917927410ac7bd947fa7ffbef7a34"
name = "inventory-shipping-monitoring"
application_url = "https://inventorymanagement.spfmktplace.tech.siwon.ca"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
  uri = "/webhooks/compliance"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "inventory_levels/update" ]
  uri = "/webhooks/inventory_levels/update"

  [[webhooks.subscriptions]]
  topics = [ "products/update" ]
  uri = "/webhooks/products/update"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/webhooks/orders/create"

[access_scopes]
scopes = "read_products,read_inventory,read_locations,read_orders"

[auth]
redirect_urls = [
  "https://inventorymanagement.spfmktplace.tech.siwon.ca/auth/callback",
  "https://inventorymanagement.spfmktplace.tech.siwon.ca/auth/shopify/callback",
  "https://inventorymanagement.spfmktplace.tech.siwon.ca/api/auth/callback",
]
