# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "832917927410ac7bd947fa7ffbef7a34"
name = "inventory-shipping-monitoring"
application_url = "https://inventorymanagement.spfmktplace.tech.siwon.ca"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  uri = "/webhooks/products/update"
  topics = [ "products/update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/inventory_levels/update"
  topics = [ "inventory_levels/update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_inventory,read_locations,read_products"

[auth]
redirect_urls = [
  "https://inventorymanagement.spfmktplace.tech.siwon.ca/auth/callback",
  "https://inventorymanagement.spfmktplace.tech.siwon.ca/auth/shopify/callback",
  "https://inventorymanagement.spfmktplace.tech.siwon.ca/api/auth/callback"
]
