import type { ActionFunctionArgs, LoaderFunctionArgs } from "react-router";
import { Form, useActionData, useLoaderData, Link } from "react-router";
import { Badge, Card, IndexTable, Button } from "@shopify/polaris";
import prisma from "../db.server";
import { authenticate } from "../shopify.server";
import { ensureMerchantSetup } from "../services/merchant-setup.server";
import { getOrCreateSubscription, hasFeature } from "../services/billing/subscription.server";
import { generateWeeklyReport } from "../services/reports/weekly-report.server";

export const loader = async ({ request }: LoaderFunctionArgs) => {
  const { session } = await authenticate.admin(request);
  const merchant = await ensureMerchantSetup(session.shop);
  const subscription = await getOrCreateSubscription(merchant.id);

  const canUseReports = hasFeature(subscription.plan, "weekly_reports");

  const reports = canUseReports
    ? await prisma.weeklyReport.findMany({
        where: { merchantId: merchant.id },
        orderBy: { weekStart: "desc" },
        take: 10,
      })
    : [];

  return {
    reports: reports.map((r) => ({
      ...r,
      weekStart: r.weekStart.toISOString(),
      weekEnd: r.weekEnd.toISOString(),
      sentAt: r.sentAt?.toISOString() ?? null,
      createdAt: r.createdAt.toISOString(),
    })),
    plan: subscription.plan,
    canUseReports,
  };
};

export const action = async ({ request }: ActionFunctionArgs) => {
  const { session } = await authenticate.admin(request);
  const merchant = await ensureMerchantSetup(session.shop);
  const subscription = await getOrCreateSubscription(merchant.id);

  if (!hasFeature(subscription.plan, "weekly_reports")) {
    return { ok: false, error: "Upgrade to Pro to use weekly reports." };
  }

  const formData = await request.formData();
  const actionType = String(formData.get("actionType") ?? "");

  if (actionType === "generate") {
    try {
      const report = await generateWeeklyReport(merchant.id);
      return { ok: true, message: "Weekly report generated successfully.", reportId: report.id };
    } catch (error) {
      return { ok: false, error: "Failed to generate report. Please try again." };
    }
  }

  return { ok: false, error: "Invalid action." };
};

export default function ReportsPage() {
  const { reports, canUseReports } = useLoaderData<typeof loader>();
  const actionData = useActionData<typeof action>();

  if (!canUseReports) {
    return (
      <s-page heading="Weekly AI Reports">
        <s-section>
          <Card>
            <div style={{ padding: "32px", textAlign: "center" }}>
              <Badge tone="info">Pro Feature</Badge>
              <h2 style={{ marginTop: "16px", marginBottom: "8px" }}>
                Get AI-powered weekly inventory reports
              </h2>
              <p style={{ color: "#637381", marginBottom: "20px" }}>
                Receive comprehensive weekly summaries with top performers, concerns, and
                actionable recommendations generated by AI.
              </p>
              <Link to="/app/billing">
                <Button variant="primary">Upgrade to Pro</Button>
              </Link>
            </div>
          </Card>
        </s-section>
      </s-page>
    );
  }

  return (
    <s-page heading="Weekly AI Reports">
      {actionData?.message && (
        <s-section>
          <div style={{ padding: "12px", background: "#d4edda", borderRadius: "8px", color: "#155724" }}>
            {actionData.message}
          </div>
        </s-section>
      )}
      {actionData?.error && (
        <s-section>
          <div style={{ padding: "12px", background: "#f8d7da", borderRadius: "8px", color: "#721c24" }}>
            {actionData.error}
          </div>
        </s-section>
      )}

      <s-section heading="Generate Report">
        <Card>
          <div style={{ padding: "16px" }}>
            <p style={{ marginBottom: "16px", color: "#637381" }}>
              Generate a comprehensive AI-powered report for the current week. The report includes
              inventory health summary, top performers, concerns, and actionable recommendations.
            </p>
            <Form method="post">
              <input type="hidden" name="actionType" value="generate" />
              <Button variant="primary" submit>
                Generate Weekly Report
              </Button>
            </Form>
          </div>
        </Card>
      </s-section>

      <s-section heading="Recent Reports">
        {reports.length === 0 ? (
          <Card>
            <div style={{ padding: "32px", textAlign: "center", color: "#637381" }}>
              No reports yet. Generate your first report above.
            </div>
          </Card>
        ) : (
          <Card>
            <IndexTable
              resourceName={{ singular: "report", plural: "reports" }}
              itemCount={reports.length}
              selectable={false}
              headings={[
                { title: "Week" },
                { title: "Summary" },
                { title: "Generated" },
                { title: "Emailed" },
              ]}
            >
              {reports.map((report, index) => (
                <IndexTable.Row id={`report-${report.id}`} key={report.id} position={index}>
                  <IndexTable.Cell>
                    {new Date(report.weekStart).toLocaleDateString()} -{" "}
                    {new Date(report.weekEnd).toLocaleDateString()}
                  </IndexTable.Cell>
                  <IndexTable.Cell>
                    <div style={{ maxWidth: "400px", whiteSpace: "pre-wrap" }}>
                      {report.summary.slice(0, 200)}
                      {report.summary.length > 200 ? "..." : ""}
                    </div>
                  </IndexTable.Cell>
                  <IndexTable.Cell>
                    {new Date(report.createdAt).toLocaleString()}
                  </IndexTable.Cell>
                  <IndexTable.Cell>
                    {report.sentAt ? (
                      <Badge tone="success">Sent</Badge>
                    ) : (
                      <Badge tone="info">Not sent</Badge>
                    )}
                  </IndexTable.Cell>
                </IndexTable.Row>
              ))}
            </IndexTable>
          </Card>
        )}
      </s-section>
    </s-page>
  );
}
